const words = [
  { word: "hombres", pista: "Plural de hombre" },
  { word: "lechuza", pista: "Ave Nocturna" },
  { word: "tren", pista: "Medio de transporte" },
  { word: "tomate", pista: "Ingrediente de una ensalada" },
  { word: "vaca", pista: "Animal que da leche" },
  { word: "avion", pista: "Transporta pasajeros por aire" },
  { word: "cafe", pista: "Planta que contiene cafeína" },
  { word: "hechizo", pista: "Lo que hace un hechicero" },
  { word: "jugo", pista: "Puede ser de distintos sabores. Calma la sed" },
  { word: "indio", pista: "Nativo de India" },
  { word: "calabozo", pista: "Sinónimo de carcel" },
  { word: "crece", pista: "Que aumenta su tamaño" },
  { word: "asensor", pista: "Sinónimo de elevador" },
  { word: "abrazar", pista: "Dar un abrazo" },
  { word: "basquet", pista: "Deporte que consiste en encestar un balón" },
  { word: "bote", pista: "Sirve para navegar" },
  { word: "duplicado", pista: "Copia" },
  { word: "puerto", pista: "Donde llegan los barcos" },
  { word: "brillante", pista: "Que brilla" },
  { word: "invisible", pista: "Que no se puede ver" },
  { word: "negar", pista: "Contrario de afirmar" },
  { word: "uva", pista: "Fruto de la vid" },
  { word: "hecho", pista: "Terminado" },
  { word: "infinito", pista: "Que no tiene fin" },
  { word: "estudiante", pista: "El que estudia es un..." },
  { word: "mio", pista: "Contrario de tuyo" },
  { word: "diez", pista: "5 X 2 = _" },
  { word: "rebelde", pista: "Que se rebela" },
  { word: "mayor", pista: "Contrario a menor" },
  { word: "dulce", pista: "Contrario a amargo" },
  { word: "peine", pista: "Sirve para peinar" },
  { word: "saborear", pista: "Probar sabores" },
  { word: "convertir", pista: "Transformar" },
  { word: "comestible", pista: "Que se puede comer" },
  { word: "desordenado", pista: "Que no tiene orden" },
  { word: "aprender", pista: "Adquirir conocimiento" },
  { word: "caro", pista: "No es barato" },
  { word: "ayudar", pista: "Brindar ayuda" },
  { word: "doce", pista: "24 ÷ 2 = _" },
  { word: "zorro", pista: "Está presente en el logo de un navegador" },
];
